spring:
  application:
    name: authentication-service
    profiles:
      active: default
server:
  address: 0.0.0.0
  port: 9090

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: "always"
logging:
  level:
    root: INFO
    com:
      example:
        authentication_service: DEBUG

com:
  example:
    authentication_service:
